### ISSUE TITLE
Intermittent Connectivity with US Modem

### ISSUE THREAD

**Issue by codepoet80** [Kazade/dreampi#1]
Discussed at length on AssemblerGames, but adding here for tracking. There seems to be timing issues when using a US Dreamcast modem that reduce the odds of a successful connection to about 1 in 3. Some games (Maximum Pool, 4x4 Evo, Starlancer) won't accept even a successful connection, and hang up immediately after connection (rage quit). Logs attached.

[BadGoodConnectionLog.txt](https://github.com/Kazade/dreampi/files/45285/BadGoodConnectionLog.txt)

[Starlancer-RageQuit.txt](https://github.com/Kazade/dreampi/files/45284/Starlancer-RageQuit.txt)

**Comment by codepoet80** [comment]
Resolved by expanding the response detection evaluation to include partial strings: "ER" instead of "ERROR" or "CO" instead of "CONNECT" since random new-line characters were seen in modem responses and screwing up the string comparison.

**Comment by Kazade** [comment]
This is still an issue. 0.98 had code to strip newlines and buffered the output - I don't suppose you could print out the buffer variable when the timeout exception is thrown?

**Comment by codepoet80** [comment]
_I'm not sure exactly which is the buffer variable, but I modified the end of send_command, thusly:_

if (datetime.now() - start).total_seconds() > timeout:
                logger.info("Last string in buffer...")
                logger.info(line)
                raise IOError("There was a timeout while waiting for a response from the modem")

_And get this output when a connection fails..._

Last string in buffer...
ATACO
Something went wrong...
Traceback (most recent call last):
  File "./dreampi.py", line 368, in main
    return process()
  File "./dreampi.py", line 345, in process
    modem.answer()
  File "./dreampi.py", line 247, in answer
    self.send_command("ATA")
  File "./dreampi.py", line 278, in send_command
    raise IOError("There was a timeout while waiting for a response from the modem")
IOError: There was a timeout while waiting for a response from the modem

_Another attempt looked like this:_

Last string in buffer...
ATAC
Something went wrong...
Traceback (most recent call last):
  File "./dreampi.py", line 368, in main
    return process()
  File "./dreampi.py", line 345, in process
    modem.answer()
  File "./dreampi.py", line 247, in answer
    self.send_command("ATA")
  File "./dreampi.py", line 278, in send_command
    raise IOError("There was a timeout while waiting for a response from the modem")
IOError: There was a timeout while waiting for a response from the modem

**Comment by jschwager** [comment]
@codepoet80 If this is still an issue please consider re-imaging your SD card with version 1.9 available via https://dreamcastlive.net/downloads/

If you're still experiencing trouble please feel free to submit a new issue. Thanks!
